# Generated by Django 3.2.6 on 2021-08-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('relyear', models.IntegerField()),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=30)),
                ('wlanguage', models.CharField(max_length=50)),
                ('songs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writers', to='nsapp.songs')),
            ],
            options={
                'db_table': 'writer',
            },
        ),
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('sage', models.IntegerField()),
                ('stotalsong', models.IntegerField()),
                ('songs', models.ManyToManyField(blank=True, null=True, related_name='singers', to='nsapp.Songs')),
            ],
            options={
                'db_table': 'singer',
            },
        ),
    ]
